{% set name = "cospar" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cospar-{{ version }}.tar.gz
  sha256: 7a9f4d333a5a95a6efbbf20bc11bf920cd9a4451c3d6499954cf58c6e29c7923

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  run_exports:
    - {{ pin_subpackage('cospar', max_pin='x.x') }}

requirements:
  host:
    - python >=3.8
    - setuptools >=40.6.0
    - wheel
    - scanpy
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.4
    - scipy >=1.5.4
    - scikit-learn >=1.1.1
    - scanpy >=1.6.0
    - pandas >=1.1.4
    - statsmodels >=0.14.0
    - plotnine >=0.7.1
    - matplotlib-base ~=3.7.0
    - fastcluster >=1.1.26
    - anndata >=0.7.5
    - numba >=0.52.0
    - scikit-misc >=0.1.3
    - leidenalg >=0.7.0
    - ete3 >=3.1.2
    - ipywidgets
    - gseapy >=0.9.13

test:
  imports:
    - cospar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ShouWenWang-Lab/cospar
  summary: 'CoSpar: integrating state and lineage information for dynamic inference'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ShouWenWang
